---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates one basic S3 bucket with default options.
Resources:
  s3bucket:
    Type: AWS::S3::Bucket
Outputs:
  s3bucketarn:
    Description: S3 bucket Arn
    Value:
      Fn::GetAtt:
        - s3bucket
        - Arn
  s3bucketname:
    Description: S3 bucket name
    Value:
      Ref: s3bucket